all: smaller smaller3 leap month

smaller: smaller.cpp
	g++ -o smaller smaller.cpp

smaller3: smaller3.cpp
	g++ -o smaller3 smaller3.cpp

leap: leap.cpp
	g++ -o leap leap.cpp

month: month.cpp
	g++ -o month month.cpp
